version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - '/**/*'
  discard-paths: yes
