version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/Android/abc.apk'
  discard-paths: yes
